### ISSUE TITLE
Add DNS Bootstrapping to get the initial Nodes

### ISSUE THREAD

**Issue by D3luxee** [mrc-g/BitMRC#1]
First, thanks for your great work it helped me a lot!

You can add DNS Bootstrapping to load initial Nodes, than you dont need to look for your hardcoded nodes.

```
addrinfo *result = NULL, hints;
    sockaddr_in  *sockaddr_ipv4;

    ZeroMemory(&hints, sizeof(hints));
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;
    hints.ai_protocol = IPPROTO_TCP;

    if (getaddrinfo("bootstrap8444.bitmessage.org", "0", &hints, &result))
    {
        printf("Node bootstrapping failed!\n");
        return 1;
    }

    for (addrinfo *ptr = result; ptr != NULL; ptr = ptr->ai_next)
    {
        if (ptr->ai_family == AF_INET)
        {

            sockaddr_ipv4 = (sockaddr_in *)ptr->ai_addr;
            /*printf(inet_ntoa(sockaddr_ipv4->sin_addr));
            printf("\n");*/
            bitmrc.connectNode(new NodeConnection(inet_ntoa(sockaddr_ipv4->sin_addr), "8444", &bitmrc));
        }
    }

    freeaddrinfo(result);
```

This is the Second Domain: bootstrap8080.bitmessage.org

Should work.

**Comment by mrc-g** [comment]
Added support  for dns bootstrap, I appreciated your help!

**Comment by D3luxee** [comment]
You should Bootstrap the second domain too.

bootstrap8080.bitmessage.org

You can use the same code, only the port of the nodes is 8080 instead of 8444.

**Comment by mrc-g** [comment]
It was like 2 AM so i just added the first one as a temporary solution.
I added it now the support to bootstrap8080: I noticed that the bootstrap ips does not work sometimes so i left the default nodes for now.

**Comment by D3luxee** [comment]
Sorry, I thought you forgot or did not see the second domain.

I did not notice any problems with the bootstrapping, but where did you get your hardcoded nodes?

I will test a bit.

**Comment by mrc-g** [comment]
I got it on a pybitmessage default know nodes and from some nodes that i got connected using bitmessage.
If you have better one just let me know.

**Comment by D3luxee** [comment]
Okay, the bootstrapping is also used by pybitmessage.

I dont have any better nodes, i was only interested where you got them from.
